title: theBluGuard
email: ashish@theBluGuard.com
description: >-
  We safeguard your digital space, allowing you to focus on what matters most.
baseurl: ""
url: "https://theblugguard.com"
twitter_username: bluguardhq
github_username:  blusafe
logo: "assets/logo.png"

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    default_lang: xml

#header_pages:
#  - get_started.md
#  - forums.md
#  - showcases.md
#  - integrations.md

collections:
  showcases:
    output: true
  examples:
    output: true
    permalink: /examples/:name/index.html

exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
